# Tugas1_2611532008.py
print("--- BIODATA MAHASISWA ---")
print("Nama    : Muhammad Rafi Firdaus")
print("NIM     : 2611532008")
print("Jurusan : Informatika")
print("Kelas   : IF B")
print("Hobi    : Bermain Game")
print()
print()
print()
print("***************")
print("***************")
print("***************")
print("***************")
print("***************")
print("***************")
print("| | | |")
print("| | | |")
print("| | | |")